theme: minima
title: Cedar's Page
author: Cedar Powers
email: cedarmpowers@gmail.com
description: A small sample of what I get up to in education, economics, and data science!
linkedin_username: cedarpowers
github_username: cedartrees


minima:
  skin: classic
  nav_pages:
    - 01_portfolio.md
    - 02_about.md

